#ifndef DISPLAY_H
#define DISPLAY_H


#define CELL_SIZE 80
#define CELL_MARGIN 19
#define GRID_SIZE (CELL_SIZE * 9)
#define FONT_SIZE (CELL_SIZE - CELL_MARGIN * 2)
#define MENU_SIZE (CELL_SIZE * 2)
#define WINDOW_WIDTH (GRID_SIZE + MENU_SIZE)
#define WINDOW_HEIGHT (GRID_SIZE)
#define BUTTON_HEIGHT 100
#define BUTTON_WIDTH 50

#endif